### ISSUE TITLE
Is this package in active use?

### ISSUE THREAD

**Issue by sameeul** [hacki11/wic#1]
Hi there,
Reaching out to you here since I don't have any other contact info.
We are just curious if this package is still active in use.

Reason: For the last 2 years, we have been developing and internally actively using a Python package "Workflow Inference Compiler". We have been calling it `wic` in all our tools. We were just about to release it and found that there is already a package with the same name but it appears inactive (no releases in last 3 years). So we are wondering if this package is actively used or not. If it is not, we were wondering if you would be considering hand over this project in PyPI to us to use this for our new package. Our package link here: [https://github.com/PolusAI/workflow-inference-compiler](https://github.com/PolusAI/workflow-inference-compiler)

**Comment by sameeul** [comment]
Settled on an alternative name :-)

**Comment by hacki11** [comment]
Glad to hear. I still see active downloads and also don't want to break it for existing users. If an active user would get a different piece of software due to an update would not be good.
